#!/bin/bash  
echo "Building build image"
sudo docker build -t my-react-app .
sudo docker image prune -f --filter label=stage=builder
echo "Build Complete, running app"
sudo docker run -p 80:80 my-react-app
echo "Cleaning up"
sudo docker rm $(docker ps -aq)